### ISSUE TITLE
Tag current state

### ISSUE THREAD

**Issue by xfbs** [MakeNowJust/crystal-diff#3]
Currently, using this package causes problems when compiling with

```yaml
dependencies:
  diff:
    github: MakeNowJust/crystal-diff
```

Because shards resolves the current version as the last tag, which is `v1.0.0`. However, the two commits after `v1.0.0` are needed to get it to compile with the current version of crystal (`0.24.1` as of this writing). Therefore, I propose to bump the version and add a `v1.0.1` tag to fix this issue. :)

Cheers, xfbs.
